### ISSUE TITLE
Node env throws error

### ISSUE THREAD

**Issue by qx2io** [zenorocha/delegate#10]
I notice that https://github.com/zenorocha/delegate/blob/master/src/closest.js#L6

```javascript
if (Element && !Element.prototype.matches) {
```

maybe change it to 

```javascript
if (typeof Element !== 'undefined' && !Element.prototype.matches) {
```

is better.

I know it should not run in node env, but our case is kind of special.

**Comment by zenorocha** [comment]
Fixed at https://github.com/zenorocha/delegate/commit/fe9bf8bbdd76fbede9d9d84e99be5f29bfafd0fd

Thanks a lot for reporting @Samaritan89!
