### ISSUE TITLE
License missing in NPM

### ISSUE THREAD

**Issue by konrad-garus** [zenorocha/delegate#12]
My PR for updating license in package.json has recently been accepted, but the update has not made it all the way to NPM. When I install the module with `npm install delegate`, the downloaded package.json still has no license statement.

Please deploy the update to NPM.

This is preventing me from using the library (and more importantly clipboard) in Java projects through WebJars. They do not let you include libraries with no valid license statement.

**Comment by zenorocha** [comment]
Done https://github.com/zenorocha/delegate/releases/tag/v3.1.2 :)

Thanks for the explanation @konrad-garus!
