### ISSUE TITLE
Don't polyfill Element.prototype.matches

### ISSUE THREAD

**Issue by niksy** [zenorocha/delegate#13]
It seems like polyfilling Element.prototype.matches with this module could be considered as unwanted side effect and instead should use ponyfill-like module e.g. https://github.com/necolas/dom-matches or https://github.com/ForbesLindesay/matches-selector

What do you think?

**Comment by zenorocha** [comment]
Hey @niksy, thanks for the suggestion. Could you describe what unwanted side effects you are having?

I'm going to close this one for now but feel free to send a pull request with your suggestions.
