### ISSUE TITLE
Closest check on SVG breaks in IE11 and Edge

### ISSUE THREAD

**Issue by nateperry** [zenorocha/delegate#14]
I discovered this issue while using clipboard.js. Originally posted here: https://github.com/zenorocha/clipboard.js/issues/390

JSFiddle: https://jsfiddle.net/nateperry/rxw2j2de/4/

### Expected behavior

As you can see in the fiddle, I am using an `a` element as the target to click, with an `<svg><use></svg>` as a child. In Internet Explorer 11 and Microsoft Edge, I would expect that the text "Hello!" is copied to my clipboard. This works in every other browser I have tested (Chrome 56, Firefox 52). I included a second `<a>` as proof that everything works without the SVG.

### Actual behavior

Instead, I get a JS error "Object doesn't support property or method 'matches'". From the best I can tell, an SVG is not considered an Element, so even though there is a polyfill for `matches`, it is does not affect SVG's.

### Browsers affected

Internet Explorer 11 and Microsoft Edge 38

**Comment by zenorocha** [comment]
Thanks for reporting @nateperry!

If you guys have any idea on how to solve this, please send a pull request. For personal reasons, I'm not going to be able to work on a bug fix in the next couple weeks.

**Comment by zenorocha** [comment]
Closing this one for now, since there was no solution offered.
