### ISSUE TITLE
Consider setting the binding of `this` to the element matching the delegation selector

### ISSUE THREAD

**Issue by philipwalton** [zenorocha/delegate#2]
I'd expect to have a way to reference the element I'm "delegating" to (i.e. that matches the passed selector), but it doesn't seem like this is supported.

For example, if I run the following code and click on a link on the page, I'd like to be able to access the link's `href` property:

``` js
delegate(document, 'a', 'click', function(event) {
  console.log(this.href);
});
```

**Comment by philipwalton** [comment]
Ok, sorry, now that I'm looking at the code I see there's a `delegateTarget` property that gets added to the event, so I suppose you can take or leave this suggestion (fwiw, I think jQuery binds the delegateTarget to `this`).

At a minimum, it'd be nice to see `delegateTarget` documented in the README.

**Comment by zenorocha** [comment]
Sorry about that @philipwalton, I've changed the API and forgot to update docs :/
