### ISSUE TITLE
delegateTarget undefined after await in async function

### ISSUE THREAD

**Issue by davidmerrique** [zenorocha/delegate#26]
Hi, I'm not sure if this can be fixed in this library or if it's a problem with regenerator.

I'm using Webpack + Babel.

`delegateTarget` is missing after an `await`

# Example
```javascript
delegate('.list', '.item', 'click', async e => {
  e.preventDefault();
  console.log(e.delegateTarget); // <li class="item">item</li>
  await doSomething();
  console.log(e.delegateTarget); // undefined
});
```

Here's how it's being transformed in [Babel](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=CYUwNiDmCGAuIAoDkA6MBLAzrJAaABKuvALZ6EDGGFA1udJgJ4B2F-I-AvAHz4DeAKHzsUABwBOIAG4hmsACIgAZtACuYWAgCUAbiH4KAe2aZDENIcgIQKUBBjwAKtHGQQsXfgD0X_AB4MAzAGTE4AImIQEjDuSJI_LwxufWgAd2hifGBDAGVDEncAC3RmK119IxMzGzBLa1twKDgQZ1d3Tx98VWZQJRKQYAEAX10gA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=6.26.0&envVersion=)

## Temporary solution
```javascript
delegate('.list', '.item', 'click', async e => {
  e.preventDefault();
  const target = e.delegateTarget;
  console.log(target); // <li class="item">item</li>
  await doSomething();
  console.log(target); // <li class="item">item</li>
});
```

Thank you

**Comment by JackPu** [comment]
@davidmerrique  maybe  3.2.0 is good!

**Comment by fregante** [comment]
Can't reproduce https://runkit.com/bfred-it/5c85bd06d3cbce0012336cb9

**Comment by davidmerrique** [comment]
@bfred-it I also can't reproduce this anymore 😅 

Off topic, but [`delegate-it`](https://github.com/bfred-it/delegate-it) is looking really nice btw. 

I've switched to [`delegated-events`](https://github.com/dgraham/delegated-events). I just like that I don't need to use `event.delegateTarget` with `delegated-events`, I can use `event.target`.

I'll go ahead and close it. Thanks!
