### ISSUE TITLE
Is there any recommendation on how to test the delegated event?

### ISSUE THREAD

**Issue by fernandofleury** [zenorocha/delegate#5]
First of all, thanks for the great library :)

I would like to know if there is any recommendation on how to test a delegated event. Maybe a way to "fire/trigger" the delegated event, to check whether the attached callback has been called.

Thanks!

**Comment by fernandofleury** [comment]
Hey, I decided to check on how you test the package, and there is this guy here: [simulant](https://github.com/Rich-Harris/simulant). I think it suits my needs, so I will close the issue!

**Comment by zenorocha** [comment]
😌
