### ISSUE TITLE
TypeError: element.matches is not a function

### ISSUE THREAD

**Issue by NMFR** [zenorocha/delegate#7]
The error "TypeError: element.matches is not a function" will be throwed in https://github.com/zenorocha/delegate/blob/master/src/closest.js#L23 if the event happens inside an iframe and the element does not match the selector.

Since the event happens in an iframe, the iframe's document is not equal to document (window.document !== iframeElement.ownerDocument).

May i suggest switching:

``` javascript
while (element && element !== document) {
``` 

In https://github.com/zenorocha/delegate/blob/master/src/closest.js#L22
by:

``` javascript
while (element && element.nodeType !== 9) {
```

**Comment by u01jmg3** [comment]
Experiencing a similar issue when using Webpack - certainly get the same error anyway

**Comment by zenorocha** [comment]
Merged #8 and released a new version of clipboard.js (v1.5.16).

Please try that out and let me know if there's any problems.

**Comment by u01jmg3** [comment]
Can a check be made for `element.matches`?

```js
if (element.matches && element.matches(selector)) return element;
```

**Comment by zenorocha** [comment]
This looks like a separate discussion @u01jmg3, is there a case where `element.matches` is undefined?

**Comment by u01jmg3** [comment]
@zenorocha, indeed, sorry for dirtying this issue. 

I haven't managed to pin down why `element.matches` is undefined -- loading dependencies with Webpack -- but having the check helps.
